name: Simple2 with inputs

on:
  push:
    branches: [ dev ]

jobs:
  print-all:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Print secret and env val from selected environment 
        run: echo secret val = ${{ secrets.SEC_VAR_1 }}, env val = ${{ vars.ENV_VAR_1 }}
      - name: Print repo secret val 
        run: echo secret val = ${{ secrets.REPO_SEC_1 }}
